export const ACTION_TYPES = {
  START_TO_FETCHING_GITHUB_ACCOUNT: Symbol("START_TO_FETCHING_GITHUB_ACCOUNT"),
  SUCCEED_TO_FETCHING_GITHUB_ACCOUNT: Symbol("SUCCEED_TO_FETCHING_GITHUB_ACCOUNT"),
  FAIL_TO_FETCHING_GITHUB_ACCOUNT: Symbol("FAIL_TO_FETCHING_GITHUB_ACCOUNT"),
};
