export const ACTION_TYPES = {
  GLOBAL_LOCATION_CHANGE: "@@router/LOCATION_CHANGE",
  SUCCEEDED_TO_FETCH_GITHUB_USER: Symbol("INITIAL_GITHUB_USER_DATA_RECORD"),
  GITHUB_USER_PAGE_START_TO_FETCH_USER: Symbol("GITHUB_USER_PAGE_START_TO_FETCH_USER"),
  GITHUB_USER_PAGE_FAILED_TO_FETCH_USER: Symbol("GITHUB_USER_PAGE_FAILED_TO_FETCH_USER"),
};
